<?php

use App\ProductCategory;
use Illuminate\Database\Seeder;

class ProductCategorySeeder extends Seeder
{
    const ProductCategories = [
        [
            'id' => '1',
            'parent_id' => null,
            'name_az' => 'Paltar, geyim',
            'name_tu' => 'Giyim, Kıyafet',
            'name_en' => 'Clothes',
            'name_ru' => 'Одежда',
        ],
        [
            'id' => '2',
            'parent_id' => '1',
            'name_az' => 'Palto',
            'name_tu' => 'Kaban',
            'name_en' => 'Coat',
            'name_ru' => 'Пальто',
        ],
        [
            'id' => '3',
            'parent_id' => '1',
            'name_az' => 'Yarımpalto',
            'name_tu' => 'Kısa kaban',
            'name_en' => 'Shortcoat',
            'name_ru' => 'Полупальто',
        ],
        [
            'id' => '4',
            'parent_id' => '1',
            'name_az' => 'Bürüncək',
            'name_tu' => 'Panço',
            'name_en' => 'cape',
            'name_ru' => 'накидка',
        ],
        [
            'id' => '5',
            'parent_id' => '1',
            'name_az' => 'Plaş',
            'name_tu' => 'Trençkot',
            'name_en' => 'Raincoat',
            'name_ru' => 'Плащ',
        ],
        [
            'id' => '6',
            'parent_id' => '1',
            'name_az' => 'Gödəkçə',
            'name_tu' => 'Ceket',
            'name_en' => 'Waistcoat',
            'name_ru' => 'куртка',
        ],
        [
            'id' => '7',
            'parent_id' => '1',
            'name_az' => 'Küləkçə',
            'name_tu' => 'Rüzgarlık',
            'name_en' => 'Windbreaker',
            'name_ru' => 'ветровка',
        ],
        [
            'id' => '8',
            'parent_id' => '1',
            'name_az' => 'Fırtınalıq',
            'name_tu' => 'Yağmurluk',
            'name_en' => 'Stormcoat',
            'name_ru' => 'непромокаемый плащ',
        ],
        [
            'id' => '9',
            'parent_id' => '1',
            'name_az' => 'Kostyum',
            'name_tu' => 'Kostüm',
            'name_en' => 'Suit',
            'name_ru' => 'костюм',
        ],
        [
            'id' => '10',
            'parent_id' => '1',
            'name_az' => 'Şalvar',
            'name_tu' => 'Pantolon',
            'name_en' => 'Pants',
            'name_ru' => 'брюки',
        ],
        [
            'id' => '11',
            'parent_id' => '1',
            'name_az' => 'Kombinezon',
            'name_tu' => 'Tulum',
            'name_en' => 'Overalls',
            'name_ru' => 'комбинезон',
        ],
        [
            'id' => '12',
            'parent_id' => '1',
            'name_az' => 'Brici',
            'name_tu' => 'Kapri',
            'name_en' => 'Midi short',
            'name_ru' => 'бриджи',
        ],
        [
            'id' => '13',
            'parent_id' => '1',
            'name_az' => 'Şort',
            'name_tu' => 'Şort',
            'name_en' => 'Short',
            'name_ru' => 'шорты',
        ],
        [
            'id' => '14',
            'parent_id' => '1',
            'name_az' => 'Jaket',
            'name_tu' => 'Hırka',
            'name_en' => 'Jacket',
            'name_ru' => 'жакет',
        ],
        [
            'id' => '15',
            'parent_id' => '1',
            'name_az' => 'Pencək',
            'name_tu' => 'Ceket',
            'name_en' => 'Coat',
            'name_ru' => 'пиджак',
        ],
        [
            'id' => '16',
            'parent_id' => '1',
            'name_az' => 'Blazer',
            'name_tu' => 'Blazer',
            'name_en' => 'Blouse',
            'name_ru' => 'блейзер',
        ],
        [
            'id' => '17',
            'parent_id' => '1',
            'name_az' => 'Köynək',
            'name_tu' => 'Gömlek',
            'name_en' => 'Shirt',
            'name_ru' => 'рубашка',
        ],
        [
            'id' => '18',
            'parent_id' => '1',
            'name_az' => 'Bluz',
            'name_tu' => 'Bluz',
            'name_en' => 'Camisole',
            'name_ru' => 'блузка',
        ],
        [
            'id' => '19',
            'parent_id' => '1',
            'name_az' => 'Mayka',
            'name_tu' => 'Atlet',
            'name_en' => 'T-shirt',
            'name_ru' => 'майка',
        ],
        [
            'id' => '20',
            'parent_id' => '1',
            'name_az' => 'Alt fufayka',
            'name_tu' => 'Termal üst',
            'name_en' => 'undershirt',
            'name_ru' => 'фуфайка(нижняя сорочка)',
        ],
        [
            'id' => '21',
            'parent_id' => '1',
            'name_az' => 'Kalson',
            'name_tu' => 'Termal alt',
            'name_en' => 'Kalson',
            'name_ru' => 'кальсоны',
        ],
        [
            'id' => '22',
            'parent_id' => '1',
            'name_az' => 'Tuman',
            'name_tu' => 'Boxer, Külot',
            'name_en' => 'Underpants',
            'name_ru' => 'трусы',
        ],
        [
            'id' => '23',
            'parent_id' => '1',
            'name_az' => 'Gecə köynəyi',
            'name_tu' => 'Gecelik',
            'name_en' => 'Nightgown',
            'name_ru' => 'ночная рубашка',
        ],
        [
            'id' => '24',
            'parent_id' => '1',
            'name_az' => 'Pijama',
            'name_tu' => 'Pijama',
            'name_en' => 'Pajamas',
            'name_ru' => 'пижама',
        ],
        [
            'id' => '25',
            'parent_id' => '1',
            'name_az' => 'Hamam xələti',
            'name_tu' => 'Bornoz',
            'name_en' => 'Bathrobe',
            'name_ru' => 'банный халат',
        ],
        [
            'id' => '26',
            'parent_id' => '1',
            'name_az' => 'Ev xələti',
            'name_tu' => 'Ev giyimi',
            'name_en' => 'Homerobe',
            'name_ru' => 'домашний халат',
        ],
        [
            'id' => '27',
            'parent_id' => '1',
            'name_az' => 'Çimərlik kostyumları',
            'name_tu' => 'Bikini, Mayo, Pareo, Deniz şortu',
            'name_en' => 'Swimwear',
            'name_ru' => 'пляжный костюм(купальник)',
        ],
        [
            'id' => '28',
            'parent_id' => '1',
            'name_az' => 'Xizək kostyumları',
            'name_tu' => 'Kayak takımları',
            'name_en' => 'Ski suits',
            'name_ru' => 'лыжный костюм',
        ],
        [
            'id' => '29',
            'parent_id' => '1',
            'name_az' => 'İstehsalat və peşə geyimi',
            'name_tu' => 'Üretim ve iş kıyafeti',
            'name_en' => 'Overalls',
            'name_ru' => 'производственная и профессиональная одежда',
        ],
        [
            'id' => '30',
            'parent_id' => '1',
            'name_az' => 'Büstqalter',
            'name_tu' => 'Sütyen',
            'name_en' => 'Bra',
            'name_ru' => 'бюстгалтер',
        ],
        [
            'id' => '31',
            'parent_id' => '1',
            'name_az' => 'Korset',
            'name_tu' => 'Korse',
            'name_en' => 'Shapewear',
            'name_ru' => 'корсет',
        ],
        [
            'id' => '32',
            'parent_id' => '1',
            'name_az' => 'Çiyinbağı',
            'name_tu' => 'Omuz askısı',
            'name_en' => 'Shoulder-strap',
            'name_ru' => 'погон',
        ],
        [
            'id' => '33',
            'parent_id' => '1',
            'name_az' => 'Yaylıq',
            'name_tu' => 'Başörtüsü',
            'name_en' => 'Shawl',
            'name_ru' => 'платок',
        ],
        [
            'id' => '34',
            'parent_id' => '1',
            'name_az' => 'Şərf',
            'name_tu' => 'Atkı',
            'name_en' => 'Scarf',
            'name_ru' => 'шарф',
        ],
        [
            'id' => '35',
            'parent_id' => '1',
            'name_az' => 'Qalstuk',
            'name_tu' => 'Kravat',
            'name_en' => 'Tie',
            'name_ru' => 'галстук',
        ],
        [
            'id' => '36',
            'parent_id' => '1',
            'name_az' => 'Əlcək və yarıməlcək',
            'name_tu' => 'Eldiver',
            'name_en' => 'Gloves and halfgloves',
            'name_ru' => 'перчатки и полуперчатки',
        ],
        [
            'id' => '37',
            'parent_id' => '1',
            'name_az' => 'İdman kostyumları',
            'name_tu' => 'Spor Takımları',
            'name_en' => 'Sport suits',
            'name_ru' => 'спортивные костюмы',
        ],
        [
            'id' => '38',
            'parent_id' => '1',
            'name_az' => 'Önlük',
            'name_tu' => 'Önlük',
            'name_en' => 'Apron',
            'name_ru' => 'фартук',
        ],
        [
            'id' => '39',
            'parent_id' => null,
            'name_az' => 'Ayaqqabı',
            'name_tu' => 'Ayakkabı',
            'name_en' => 'Shoes',
            'name_ru' => 'Oбувь:',
        ],
        [
            'id' => '40',
            'parent_id' => '39',
            'name_az' => 'Xizək üçün çəkmə',
            'name_tu' => 'Kar botu',
            'name_en' => 'Ski boots',
            'name_ru' => 'лыжные ботинки',
        ],
        [
            'id' => '41',
            'parent_id' => '39',
            'name_az' => 'Snoubord üçün çəkmə',
            'name_tu' => 'Snowboard botları',
            'name_en' => 'Snowboarding boots',
            'name_ru' => 'ботинки для сноуборда',
        ],
        [
            'id' => '42',
            'parent_id' => '39',
            'name_az' => 'Klassik',
            'name_tu' => 'Klasik',
            'name_en' => 'Classic',
            'name_ru' => 'классическая',
        ],
        [
            'id' => '43',
            'parent_id' => '39',
            'name_az' => 'Derbi',
            'name_tu' => 'Derbi',
            'name_en' => 'Derby',
            'name_ru' => 'дерби',
        ],
        [
            'id' => '44',
            'parent_id' => '39',
            'name_az' => 'Lofer',
            'name_tu' => 'Loafer',
            'name_en' => 'Loafer',
            'name_ru' => 'лоферы',
        ],
        [
            'id' => '45',
            'parent_id' => '39',
            'name_az' => 'Oksford',
            'name_tu' => 'Oxford',
            'name_en' => 'Oxford',
            'name_ru' => 'оксфорды',
        ],
        [
            'id' => '46',
            'parent_id' => '39',
            'name_az' => 'Yarımboğaz ayaqqabı',
            'name_tu' => 'Bot',
            'name_en' => 'Half boot(mid-calf boot)',
            'name_ru' => 'полуботинки',
        ],
        [
            'id' => '47',
            'parent_id' => '39',
            'name_az' => 'Krassovka',
            'name_tu' => 'Sneaker, Spor ayakabı',
            'name_en' => 'Sneaker',
            'name_ru' => 'кроссовки',
        ],
        [
            'id' => '48',
            'parent_id' => '39',
            'name_az' => 'Mokasin',
            'name_tu' => 'Babet',
            'name_en' => 'Moccasin',
            'name_ru' => 'мокасины',
        ],
        [
            'id' => '49',
            'parent_id' => '39',
            'name_az' => 'Espadril',
            'name_tu' => 'Espardil',
            'name_en' => 'Espadril',
            'name_ru' => 'эспадрильи',
        ],
        [
            'id' => '50',
            'parent_id' => '39',
            'name_az' => 'Səndəl',
            'name_tu' => 'Sandalet',
            'name_en' => 'Sandal',
            'name_ru' => 'сандалии',
        ],
        [
            'id' => '51',
            'parent_id' => '39',
            'name_az' => 'Ev tərliyi',
            'name_tu' => 'Terlik',
            'name_en' => 'Slippers',
            'name_ru' => 'домашняя обувь( тапочки)',
        ],
        [
            'id' => '52',
            'parent_id' => null,
            'name_az' => 'Ayaqqabı qadın üçün',
            'name_tu' => 'Kadın Ayakkabı',
            'name_en' => 'Womens shoes',
            'name_ru' => 'Женская обувь:',
        ],
        [
            'id' => '53',
            'parent_id' => '52',
            'name_az' => 'Xizək üçün çəkmə',
            'name_tu' => 'Kar botu',
            'name_en' => 'Ski boots',
            'name_ru' => 'лыжные ботинки',
        ],
        [
            'id' => '54',
            'parent_id' => '52',
            'name_az' => 'Snoubord üçün çəkmə',
            'name_tu' => 'Snowboard botları',
            'name_en' => 'Snowboarding boots',
            'name_ru' => 'ботинки для сноуборда',
        ],
        [
            'id' => '55',
            'parent_id' => '52',
            'name_az' => 'Derbi',
            'name_tu' => 'Derbi',
            'name_en' => 'Derby',
            'name_ru' => 'Дерби',
        ],
        [
            'id' => '56',
            'parent_id' => '39',
            'name_az' => 'Slip-on',
            'name_tu' => 'Slip-on',
            'name_en' => 'Slip-on',
            'name_ru' => 'слипоны',
        ],
        [
            'id' => '57',
            'parent_id' => '52',
            'name_az' => 'Lofer',
            'name_tu' => 'Loafer',
            'name_en' => 'Loafer',
            'name_ru' => 'лоферы',
        ],
        [
            'id' => '58',
            'parent_id' => '39',
            'name_az' => 'Uzunboğaz çəkmə',
            'name_tu' => 'Çizme',
            'name_en' => 'Knee-high boots',
            'name_ru' => 'высокие сапоги',
        ],
        [
            'id' => '59',
            'parent_id' => '39',
            'name_az' => 'Yarımboğaz çəkmə',
            'name_tu' => 'Bot',
            'name_en' => 'Mid-calf boots',
            'name_ru' => 'полусапоги',
        ],
        [
            'id' => '60',
            'parent_id' => '39',
            'name_az' => 'Hündurdaban',
            'name_tu' => 'Topuklu',
            'name_en' => 'Heels',
            'name_ru' => 'высокий каблук',
        ],
        [
            'id' => '61',
            'parent_id' => '52',
            'name_az' => 'Espadril',
            'name_tu' => 'Espardil',
            'name_en' => 'Espadril',
            'name_ru' => 'эспадрильи',
        ],
        [
            'id' => '62',
            'parent_id' => '39',
            'name_az' => 'Baletka',
            'name_tu' => 'Babet',
            'name_en' => 'Baletka',
            'name_ru' => 'балетки',
        ],
        [
            'id' => '63',
            'parent_id' => '52',
            'name_az' => 'Səndəl',
            'name_tu' => 'Sandalet',
            'name_en' => 'Sandal',
            'name_ru' => 'сандалии',
        ],
        [
            'id' => '64',
            'parent_id' => '52',
            'name_az' => 'Krassovka',
            'name_tu' => 'Sneaker, Spor ayakabı',
            'name_en' => 'Sneaker',
            'name_ru' => 'кроссовки',
        ],
        [
            'id' => '65',
            'parent_id' => '52',
            'name_az' => 'Ev tərliyi',
            'name_tu' => 'Terlik',
            'name_en' => 'Slippers',
            'name_ru' => 'домашняя обувь( тапочки)',
        ],
        [
            'id' => '66',
            'parent_id' => null,
            'name_az' => 'Geyim aksesuarları',
            'name_tu' => 'Kıyafet aksesuarları',
            'name_en' => 'Accessories',
            'name_ru' => 'Аксессуары:',
        ],
        [
            'id' => '67',
            'parent_id' => '66',
            'name_az' => 'Qayış',
            'name_tu' => 'Kemer',
            'name_en' => 'Belt',
            'name_ru' => 'ремень',
        ],
        [
            'id' => '68',
            'parent_id' => '66',
            'name_az' => 'Şərf',
            'name_tu' => 'Atkı, Şal',
            'name_en' => 'Scarf',
            'name_ru' => 'шарф',
        ],
        [
            'id' => '69',
            'parent_id' => '66',
            'name_az' => 'Əlcək',
            'name_tu' => 'Eldiven',
            'name_en' => 'Gloves',
            'name_ru' => 'перчатки',
        ],
        [
            'id' => '70',
            'parent_id' => '66',
            'name_az' => 'Bijuteriya',
            'name_tu' => 'Bijuteri, Aksesuar',
            'name_en' => 'Bijouterie',
            'name_ru' => 'бижутерия',
        ],
        [
            'id' => '71',
            'parent_id' => '66',
            'name_az' => 'Portmone',
            'name_tu' => 'Cüzdan',
            'name_en' => 'Wallet',
            'name_ru' => 'портмоне',
        ],
        [
            'id' => '72',
            'parent_id' => '66',
            'name_az' => 'Papaq',
            'name_tu' => 'Bere, Şapka',
            'name_en' => 'Hat',
            'name_ru' => 'шапка',
        ],
        [
            'id' => '73',
            'parent_id' => '66',
            'name_az' => 'Qalstuk',
            'name_tu' => 'Kravat',
            'name_en' => 'Tie',
            'name_ru' => 'галстук',
        ],
        [
            'id' => '74',
            'parent_id' => '66',
            'name_az' => 'Çanta',
            'name_tu' => 'Çanta',
            'name_en' => 'Bag',
            'name_ru' => 'сумка',
        ],
        [
            'id' => '75',
            'parent_id' => '66',
            'name_az' => 'Eynək',
            'name_tu' => 'Gözlük',
            'name_en' => 'Sunglasses',
            'name_ru' => 'очки',
        ],
        [
            'id' => '76',
            'parent_id' => '66',
            'name_az' => 'Çətir',
            'name_tu' => 'Şemsiye',
            'name_en' => 'Umbrella',
            'name_ru' => 'зонт',
        ],
        [
            'id' => '77',
            'parent_id' => '66',
            'name_az' => 'Saat',
            'name_tu' => 'Saat',
            'name_en' => 'Watch',
            'name_ru' => 'часы',
        ],
        [
            'id' => '78',
            'parent_id' => null,
            'name_az' => 'Geyim aksesuarları qadın üçün',
            'name_tu' => 'Kadın kıyafet aksesuarları',
            'name_en' => 'Accessories for women',
            'name_ru' => 'Аксессуары для женщин:',
        ],
        [
            'id' => '79',
            'parent_id' => '66',
            'name_az' => 'Makiyaj çantaları',
            'name_tu' => 'Kozmetik çantası',
            'name_en' => 'Beauty case',
            'name_ru' => 'косметичка',
        ],
        [
            'id' => '80',
            'parent_id' => '78',
            'name_az' => 'Qayış',
            'name_tu' => 'Kəmər',
            'name_en' => 'Belt',
            'name_ru' => 'ремень',
        ],
        [
            'id' => '81',
            'parent_id' => '78',
            'name_az' => 'Əlcək',
            'name_tu' => 'Eldiven',
            'name_en' => 'Gloves',
            'name_ru' => 'перчатки',
        ],
        [
            'id' => '82',
            'parent_id' => '78',
            'name_az' => 'Çətir',
            'name_tu' => 'Şemsiye',
            'name_en' => 'Umbrella',
            'name_ru' => 'зонт',
        ],
        [
            'id' => '83',
            'parent_id' => '78',
            'name_az' => 'Portmone',
            'name_tu' => 'Cüzdan',
            'name_en' => 'Wallet',
            'name_ru' => 'портмоне',
        ],
        [
            'id' => '84',
            'parent_id' => '78',
            'name_az' => 'Eynək',
            'name_tu' => 'Gözlük',
            'name_en' => 'Sunglasses',
            'name_ru' => 'очки',
        ],
        [
            'id' => '85',
            'parent_id' => '78',
            'name_az' => 'Şərf',
            'name_tu' => 'Atkı',
            'name_en' => 'Scarf',
            'name_ru' => 'шарф',
        ],
        [
            'id' => '86',
            'parent_id' => '78',
            'name_az' => 'Papaq',
            'name_tu' => 'Bere, Şapka',
            'name_en' => 'Hat',
            'name_ru' => 'шапка',
        ],
        [
            'id' => '87',
            'parent_id' => '78',
            'name_az' => 'Bijuteriya',
            'name_tu' => 'Bijuteri, Aksesuar',
            'name_en' => 'Bijouterie',
            'name_ru' => 'бижутерия',
        ],
        [
            'id' => '88',
            'parent_id' => '78',
            'name_az' => 'Çanta',
            'name_tu' => 'Çanta',
            'name_en' => 'Bag',
            'name_ru' => 'сумка',
        ],
        [
            'id' => '89',
            'parent_id' => '78',
            'name_az' => 'Saat',
            'name_tu' => 'Saat',
            'name_en' => 'Watch',
            'name_ru' => 'часы',
        ],
        [
            'id' => '90',
            'parent_id' => '78',
            'name_az' => 'Çətir',
            'name_tu' => 'Şemsiye',
            'name_en' => 'Umbrella',
            'name_ru' => 'зонт',
        ],
        [
            'id' => '91',
            'parent_id' => '66',
            'name_az' => 'Saç aksesuarları',
            'name_tu' => 'Saç aksesuarları',
            'name_en' => 'Hair accessories',
            'name_ru' => 'аксессуары для волос',
        ],
        [
            'id' => '92',
            'parent_id' => null,
            'name_az' => 'Kompüter, Elektronika',
            'name_tu' => 'Bilgisayar, Elektronik',
            'name_en' => 'Computer',
            'name_ru' => 'Компьютер',
        ],
        [
            'id' => '93',
            'parent_id' => '92',
            'name_az' => 'Noutbuk',
            'name_tu' => 'Dizüstü bilgisayar',
            'name_en' => 'Laptop',
            'name_ru' => 'ноутбук',
        ],
        [
            'id' => '94',
            'parent_id' => '92',
            'name_az' => 'Netbuk',
            'name_tu' => 'Dizüstü bilgisayar',
            'name_en' => 'Netbook',
            'name_ru' => 'нетбук',
        ],
        [
            'id' => '95',
            'parent_id' => '92',
            'name_az' => 'Masaüstü komputer',
            'name_tu' => 'Masaüstü Bilgisayar',
            'name_en' => 'Desktop computer',
            'name_ru' => 'Настольный (стационарный) компьютер',
        ],
        [
            'id' => '96',
            'parent_id' => '92',
            'name_az' => 'Monoblok',
            'name_tu' => 'Monoblok',
            'name_en' => 'Monoblock',
            'name_ru' => 'моноблок',
        ],
        [
            'id' => '97',
            'parent_id' => '92',
            'name_az' => 'Oyun kompüteri',
            'name_tu' => 'Oyun bilgisayarı',
            'name_en' => 'Game computer',
            'name_ru' => 'игровой компьютер',
        ],
        [
            'id' => '98',
            'parent_id' => '92',
            'name_az' => 'Monitor',
            'name_tu' => 'Monitör',
            'name_en' => 'Monitor',
            'name_ru' => 'монитор',
        ],
        [
            'id' => '99',
            'parent_id' => '92',
            'name_az' => 'Printer',
            'name_tu' => 'Yazıcı',
            'name_en' => 'Printer',
            'name_ru' => 'принтер',
        ],
        [
            'id' => '100',
            'parent_id' => '92',
            'name_az' => 'Xarici toplayıcı disklər HDD',
            'name_tu' => 'Harici depolama sürücüleri HDD',
            'name_en' => 'External storage drives HDD',
            'name_ru' => 'внешний hdd-накопитель',
        ],
        [
            'id' => '101',
            'parent_id' => '92',
            'name_az' => 'Kartric',
            'name_tu' => 'Kartuş',
            'name_en' => 'Cartridge',
            'name_ru' => 'картридж',
        ],
        [
            'id' => '102',
            'parent_id' => '92',
            'name_az' => 'Proyektor',
            'name_tu' => 'Projektör',
            'name_en' => 'Projector',
            'name_ru' => 'проектор',
        ],
        [
            'id' => '103',
            'parent_id' => '92',
            'name_az' => 'Siçan',
            'name_tu' => 'Mause',
            'name_en' => 'Mouse',
            'name_ru' => 'Компьютерная мышь',
        ],
        [
            'id' => '104',
            'parent_id' => '92',
            'name_az' => 'Prezentasiya üçün pult',
            'name_tu' => 'Sunum uzaktan kumandası',
            'name_en' => 'Presentation remote control',
            'name_ru' => 'пульт для презентаций',
        ],
        [
            'id' => '105',
            'parent_id' => '92',
            'name_az' => 'Noutbuk üçün çanta',
            'name_tu' => 'Dizüstü bilgisayar çantası',
            'name_en' => 'Laptop bag',
            'name_ru' => 'сумка для ноутбука',
        ],
        [
            'id' => '106',
            'parent_id' => '92',
            'name_az' => 'Noutbuk üçün altlıq',
            'name_tu' => 'Dizüstü Bilgisayar Kılıf',
            'name_en' => 'Laptop case',
            'name_ru' => 'кейс для ноутбука',
        ],
        [
            'id' => '107',
            'parent_id' => '92',
            'name_az' => 'Fleş toplayıcı',
            'name_tu' => 'USB Bellek',
            'name_en' => 'Flash collector',
            'name_ru' => 'флеш-накопитель ',
        ],
        [
            'id' => '108',
            'parent_id' => '92',
            'name_az' => 'Modem',
            'name_tu' => 'Modem',
            'name_en' => 'Modem',
            'name_ru' => 'модем',
        ],
        [
            'id' => '109',
            'parent_id' => '92',
            'name_az' => 'Xarici toplayıcı disklər SSD',
            'name_tu' => 'Harici depolama sürücüleri HDD',
            'name_en' => 'External storage drives SSD',
            'name_ru' => ' Внешние SSD накопители',
        ],
        [
            'id' => '110',
            'parent_id' => null,
            'name_az' => 'Oyun konsolları',
            'name_tu' => 'Oyun konsolları',
            'name_en' => 'Game consoles',
            'name_ru' => 'Игровые приставки',
        ],
        [
            'id' => '111',
            'parent_id' => '110',
            'name_az' => 'Playstation',
            'name_tu' => 'Playstation',
            'name_en' => 'Playstation',
            'name_ru' => 'Playstation',
        ],
        [
            'id' => '112',
            'parent_id' => '110',
            'name_az' => 'Xbox',
            'name_tu' => 'Xbox',
            'name_en' => 'Xbox',
            'name_ru' => 'Xbox',
        ],
        [
            'id' => '113',
            'parent_id' => '110',
            'name_az' => 'DVD',
            'name_tu' => 'DVD',
            'name_en' => 'DVD',
            'name_ru' => 'DVD',
        ],
        [
            'id' => '114',
            'parent_id' => '110',
            'name_az' => 'DVD və CD disklər',
            'name_tu' => 'DVD ve CD diskleri',
            'name_en' => 'DVD and CD disks',
            'name_ru' => 'DVD и CD',
        ],
        [
            'id' => '115',
            'parent_id' => '110',
            'name_az' => 'Nintendo',
            'name_tu' => 'Oyun kolu',
            'name_en' => 'Nintendo',
            'name_ru' => 'Nintendo',
        ],
        [
            'id' => '116',
            'parent_id' => null,
            'name_az' => 'Kosmetik vasitələr',
            'name_tu' => 'Makyaj malzemeleri',
            'name_en' => 'Cosmetics',
            'name_ru' => 'Косметические средства',
        ],
        [
            'id' => '117',
            'parent_id' => '116',
            'name_az' => 'Kirşan',
            'name_tu' => 'Pudra',
            'name_en' => 'Powder',
            'name_ru' => 'пудра',
        ],
        [
            'id' => '118',
            'parent_id' => '116',
            'name_az' => 'Tonal krem',
            'name_tu' => 'fondöten',
            'name_en' => 'Foundation cream',
            'name_ru' => 'тональный крем',
        ],
        [
            'id' => '119',
            'parent_id' => '116',
            'name_az' => 'Konsiler',
            'name_tu' => 'Kapatıcı',
            'name_en' => 'Consealer',
            'name_ru' => 'консилер',
        ],
        [
            'id' => '120',
            'parent_id' => '116',
            'name_az' => 'Ənlik',
            'name_tu' => 'Allık',
            'name_en' => 'Blushes',
            'name_ru' => 'румяна',
        ],
        [
            'id' => '121',
            'parent_id' => '116',
            'name_az' => 'Tuş',
            'name_tu' => 'Maskara',
            'name_en' => 'Mascara',
            'name_ru' => 'тушь',
        ],
        [
            'id' => '122',
            'parent_id' => '116',
            'name_az' => 'Göz kölgəsi',
            'name_tu' => 'Göz farı',
            'name_en' => 'Eye shadow',
            'name_ru' => 'Тени для век',
        ],
        [
            'id' => '123',
            'parent_id' => '116',
            'name_az' => 'Göz qələmi',
            'name_tu' => 'Göz kalemi',
            'name_en' => 'Eye pencil',
            'name_ru' => 'карандаш для глаз',
        ],
        [
            'id' => '124',
            'parent_id' => '116',
            'name_az' => 'Dodaq boyası',
            'name_tu' => 'Ruj',
            'name_en' => 'Lipstick',
            'name_ru' => 'Губная помада',
        ],
        [
            'id' => '125',
            'parent_id' => '116',
            'name_az' => 'Bronzer',
            'name_tu' => 'Bronzer',
            'name_en' => 'Bronzer',
            'name_ru' => 'бронзер',
        ],
        [
            'id' => '126',
            'parent_id' => '116',
            'name_az' => 'Korrektor',
            'name_tu' => 'Corrector',
            'name_en' => 'Corrector',
            'name_ru' => 'корректор',
        ],
        [
            'id' => '127',
            'parent_id' => '116',
            'name_az' => 'Layner',
            'name_tu' => 'eyeliner',
            'name_en' => 'Liner',
            'name_ru' => 'лайнер',
        ],
        [
            'id' => '128',
            'parent_id' => '116',
            'name_az' => 'Praymer',
            'name_tu' => 'Makyaj Bazı',
            'name_en' => 'Face primer',
            'name_ru' => 'праймер',
        ],
        [
            'id' => '129',
            'parent_id' => '116',
            'name_az' => 'Haylayter',
            'name_tu' => 'Highlighter',
            'name_en' => 'Highlighter',
            'name_ru' => 'хайлайтер',
        ],
        [
            'id' => '130',
            'parent_id' => '116',
            'name_az' => 'Qaş qələmi',
            'name_tu' => 'Kaş kalemi',
            'name_en' => 'Eyebrow pencil',
            'name_ru' => 'Карандаш для бровей',
        ],
        [
            'id' => '131',
            'parent_id' => '116',
            'name_az' => 'Qaş kirşanı',
            'name_tu' => 'Kaş farı',
            'name_en' => 'Eyebrow powder',
            'name_ru' => 'пудра для бровей',
        ],
        [
            'id' => '132',
            'parent_id' => '116',
            'name_az' => 'Dırnaq lakı',
            'name_tu' => 'Oje',
            'name_en' => 'Nail polish',
            'name_ru' => 'Лак для ногтей',
        ],
        [
            'id' => '133',
            'parent_id' => null,
            'name_az' => 'Telefon və telefon üçün aksesuarlar',
            'name_tu' => 'Telefon',
            'name_en' => 'Phone',
            'name_ru' => 'Телефон',
        ],
        [
            'id' => '134',
            'parent_id' => '133',
            'name_az' => 'Mobil telefon',
            'name_tu' => 'Cep telefonu',
            'name_en' => 'Mobile phone',
            'name_ru' => 'мобильный телефон',
        ],
        [
            'id' => '135',
            'parent_id' => '133',
            'name_az' => 'Ev və ofis telefonu',
            'name_tu' => 'Ev ve ofis telefonu',
            'name_en' => 'Home and office phone',
            'name_ru' => 'домашний и офисный телефон',
        ],
        [
            'id' => '136',
            'parent_id' => '133',
            'name_az' => 'Smart saatlar',
            'name_tu' => 'Akıllı saatler',
            'name_en' => 'Smart watches',
            'name_ru' => 'Умные часы ( Смарт-часы)',
        ],
        [
            'id' => '137',
            'parent_id' => null,
            'name_az' => 'Telefon(telefon üçün aksesuarlar)',
            'name_tu' => 'Telefon aksesuarları',
            'name_en' => 'Phone accessories:',
            'name_ru' => 'аксессуары для телефона',
        ],
        [
            'id' => '138',
            'parent_id' => '133',
            'name_az' => 'Qulaqlıqlar',
            'name_tu' => 'Kulaklıklar',
            'name_en' => 'Headphones',
            'name_ru' => 'Наушники',
        ],
        [
            'id' => '139',
            'parent_id' => '133',
            'name_az' => 'Ekran qoruyucuları',
            'name_tu' => 'Ekran koruyucusu',
            'name_en' => 'Screensaver',
            'name_ru' => 'защита дисплея',
        ],
        [
            'id' => '140',
            'parent_id' => '137',
            'name_az' => 'Keyslər',
            'name_tu' => 'Kılıf',
            'name_en' => 'Cases',
            'name_ru' => 'кейс для телефона',
        ],
        [
            'id' => '141',
            'parent_id' => '133',
            'name_az' => 'Portativ akkumlyator',
            'name_tu' => 'Taşınabilir akümülatör',
            'name_en' => 'Portable accumulator',
            'name_ru' => 'портативный аккумулятор для телефона (power b',
        ],
        [
            'id' => '142',
            'parent_id' => '133',
            'name_az' => 'Adapter',
            'name_tu' => 'Adaptör',
            'name_en' => 'Adapter',
            'name_ru' => 'Адаптер',
        ],
        [
            'id' => '143',
            'parent_id' => '133',
            'name_az' => 'Yaddaş qurğuları',
            'name_tu' => 'Bellek aygıtları',
            'name_en' => 'Memory devices',
            'name_ru' => 'Устройства памяти телефона',
        ],
        [
            'id' => '144',
            'parent_id' => '133',
            'name_az' => 'USB və AUX kabelləri',
            'name_tu' => 'USB ve AUX kabloları',
            'name_en' => 'USB and AUX cables',
            'name_ru' => 'Кабель для телефона USB и AUX',
        ],
        [
            'id' => '145',
            'parent_id' => '133',
            'name_az' => 'Selfi çubuqları',
            'name_tu' => 'Selfie çubukları',
            'name_en' => 'Selfie sticks',
            'name_ru' => 'селфи-палка',
        ],
        [
            'id' => '146',
            'parent_id' => null,
            'name_az' => 'Məişət avadanlıqları(Böyük məişət texnikası)',
            'name_tu' => 'Büyük ev aletleri:',
            'name_en' => 'Large home appliances:',
            'name_ru' => 'Крупная бытовая техника ',
        ],
        [
            'id' => '147',
            'parent_id' => '146',
            'name_az' => 'Soyuducu',
            'name_tu' => 'Buzdolabı',
            'name_en' => 'Refrigerator',
            'name_ru' => ' Холодильник',
        ],
        [
            'id' => '148',
            'parent_id' => '146',
            'name_az' => 'Dondurucu kamera',
            'name_tu' => 'Dondurucu',
            'name_en' => 'Freezer',
            'name_ru' => 'Морозильная камера',
        ],
        [
            'id' => '149',
            'parent_id' => '146',
            'name_az' => 'Paltaryuyan maşın',
            'name_tu' => 'Çamaşır makinesi',
            'name_en' => 'Washing machine',
            'name_ru' => ' Стиральная машина',
        ],
        [
            'id' => '150',
            'parent_id' => '146',
            'name_az' => 'Quruducu maşın',
            'name_tu' => 'Kurutma makinesi',
            'name_en' => 'Drying machine',
            'name_ru' => 'сушильная машина',
        ],
        [
            'id' => '151',
            'parent_id' => '146',
            'name_az' => 'Buxar dolabı',
            'name_tu' => 'Buhar dolabı',
            'name_en' => 'Steam cabinet',
            'name_ru' => 'Паровой шкаф ',
        ],
        [
            'id' => '152',
            'parent_id' => '146',
            'name_az' => 'Qabyuyan maşın',
            'name_tu' => 'Bulaşık makinesi',
            'name_en' => 'Dishwasher',
            'name_ru' => ' Посудомоечная машина',
        ],
        [
            'id' => '153',
            'parent_id' => '146',
            'name_az' => 'Televizor',
            'name_tu' => 'Televizyon',
            'name_en' => 'Television',
            'name_ru' => 'телевизор',
        ],
        [
            'id' => '154',
            'parent_id' => '146',
            'name_az' => 'Kondisioner',
            'name_tu' => 'Klimalar',
            'name_en' => 'Conditioners',
            'name_ru' => 'Кондиционер ',
        ], [
            'id' => '155',
            'parent_id' => '146',
            'name_az' => 'Aspirator',
            'name_tu' => 'Aspiratör',
            'name_en' => 'Aspirator',
            'name_ru' => 'Аспиратор ',
        ], [
            'id' => '156',
            'parent_id' => '146',
            'name_az' => 'Bişirmə paneli',
            'name_tu' => 'Pişirme paneli',
            'name_en' => 'Cooking panel',
            'name_ru' => 'варочная панель',
        ], [
            'id' => '157',
            'parent_id' => '146',
            'name_az' => 'Soba',
            'name_tu' => 'Soba, fırın, ocak',
            'name_en' => 'Stove',
            'name_ru' => 'духовка',
        ], [
            'id' => '158',
            'parent_id' => '146',
            'name_az' => 'Plitə',
            'name_tu' => 'Isıtıcı',
            'name_en' => 'Heater',
            'name_ru' => 'кухонная плита,',
        ], [
            'id' => '159',
            'parent_id' => null,
            'name_az' => 'Məişət avadanlıqları(Kiçik məişət texnikası)',
            'name_tu' => 'Küçük ev aletleri:',
            'name_en' => 'Small home appliances:',
            'name_ru' => 'Мелкая бытовая техника ',
        ], [
            'id' => '160',
            'parent_id' => '159',
            'name_az' => 'Blender',
            'name_tu' => 'Blender',
            'name_en' => 'Blender',
            'name_ru' => 'блендер',
        ], [
            'id' => '161',
            'parent_id' => '159',
            'name_az' => 'Mətbəx tərəzisi',
            'name_tu' => 'Mutfak terazileri',
            'name_en' => 'Kitchen scales',
            'name_ru' => ' кухонные весы',
        ], [
            'id' => '162',
            'parent_id' => '159',
            'name_az' => 'Mətbəx kombaynı',
            'name_tu' => 'Mutfak Robotları',
            'name_en' => 'Kitchen combine',
            'name_ru' => 'кухонный комбайн',
        ], [
            'id' => '163',
            'parent_id' => '159',
            'name_az' => 'Mikser',
            'name_tu' => 'Mikser',
            'name_en' => 'Mixer',
            'name_ru' => 'миксер',
        ], [
            'id' => '164',
            'parent_id' => '159',
            'name_az' => 'Ətçəkən maşın',
            'name_tu' => 'Kıyma Makinesi',
            'name_en' => 'Meat Grinder Machine',
            'name_ru' => 'Мясорубка',
        ], [
            'id' => '165',
            'parent_id' => '159',
            'name_az' => 'Multibişiricilər',
            'name_tu' => 'Multicooker Çok Amaçlı Pişirici',
            'name_en' => 'Multicooker',
            'name_ru' => 'Мультиварка ',
        ], [
            'id' => '166',
            'parent_id' => '159',
            'name_az' => 'Mikrodalğalı soba',
            'name_tu' => 'Mikrodalga',
            'name_en' => 'Microwave',
            'name_ru' => 'Микроволновая печь ( СВЧ-печь)',
        ], [
            'id' => '167',
            'parent_id' => '159',
            'name_az' => 'Çörək bişrən',
            'name_tu' => 'Fırın',
            'name_en' => 'Baker',
            'name_ru' => 'Хлебопечка (хлебопечь)',
        ], [
            'id' => '168',
            'parent_id' => '159',
            'name_az' => 'Elektrik sobası',
            'name_tu' => 'Elektrikli fırın',
            'name_en' => 'Electric oven',
            'name_ru' => 'Электрическая духовка ',
        ], [
            'id' => '169',
            'parent_id' => '159',
            'name_az' => 'Toster',
            'name_tu' => 'Tost makinası',
            'name_en' => 'Toaster',
            'name_ru' => 'тостер',
        ], [
            'id' => '170',
            'parent_id' => '159',
            'name_az' => 'Buxarlı bişirici',
            'name_tu' => 'Buharlı ocak',
            'name_en' => 'Steam cooker',
            'name_ru' => 'Пароварка',
        ], [
            'id' => '171',
            'parent_id' => '159',
            'name_az' => 'Fen',
            'name_tu' => 'Saç kurutma makinesi',
            'name_en' => 'Hair-drier',
            'name_ru' => 'фен',
        ], [
            'id' => '172',
            'parent_id' => '159',
            'name_az' => 'Fritoz',
            'name_tu' => 'Fritöz',
            'name_en' => 'Deep fryer',
            'name_ru' => 'Фритюрница',
        ], [
            'id' => '173',
            'parent_id' => '159',
            'name_az' => 'Elektrik çaydan',
            'name_tu' => 'Su ısıtıcısı',
            'name_en' => 'Kettle',
            'name_ru' => 'Электрический чайник ',
        ], [
            'id' => '174',
            'parent_id' => '159',
            'name_az' => 'Qəhvə dəmləyən',
            'name_tu' => 'Kahve makinesi',
            'name_en' => 'Coffee brewer',
            'name_ru' => 'Кофеварка',
        ], [
            'id' => '175',
            'parent_id' => '159',
            'name_az' => 'Qəhvə üyüdən',
            'name_tu' => 'Kahve öğütücü',
            'name_en' => 'Coffee grinder',
            'name_ru' => 'Кофемолка',
        ], [
            'id' => '176',
            'parent_id' => '159',
            'name_az' => 'Şirəçəkən',
            'name_tu' => 'Meyve Sıkacağı',
            'name_en' => 'Juicer',
            'name_ru' => 'Соковыжималка',
        ], [
            'id' => '177',
            'parent_id' => '159',
            'name_az' => 'Ütü',
            'name_tu' => 'Ütü',
            'name_en' => 'İron',
            'name_ru' => 'утюг',
        ], [
            'id' => '178',
            'parent_id' => '159',
            'name_az' => 'Tozsoran',
            'name_tu' => 'Elektrikli süpürge',
            'name_en' => 'Vacuum cleaner',
            'name_ru' => 'Пылесос',
        ], [
            'id' => '179',
            'parent_id' => '159',
            'name_az' => 'Buxarlı təmizləyici',
            'name_tu' => 'Buhar temizleyicisi',
            'name_en' => 'Steam cleaner',
            'name_ru' => 'Пароочиститель',
        ], [
            'id' => '180',
            'parent_id' => null,
            'name_az' => 'Maşın ehtiyat hissələri',
            'name_tu' => 'Otomobil yedek parçaları',
            'name_en' => 'Car spare parts',
            'name_ru' => 'Автомобильные запчасти',
        ], [
            'id' => '181',
            'parent_id' => '180',
            'name_az' => 'Mühərrik hissələri',
            'name_tu' => 'Oto gövde parçaları',
            'name_en' => 'Auto body parts',
            'name_ru' => ' Детали двигателя ',
        ], [
            'id' => '182',
            'parent_id' => '180',
            'name_az' => 'Kuzov(əsas) hissələri',
            'name_tu' => 'Motor parçaları',
            'name_en' => 'Engine parts',
            'name_ru' => 'детали (основные) кузова',
        ], [
            'id' => '183',
            'parent_id' => '180',
            'name_az' => 'Fara',
            'name_tu' => 'Farlar:',
            'name_en' => 'Headlights:',
            'name_ru' => 'фара',
        ], [
            'id' => '184',
            'parent_id' => '180',
            'name_az' => 'Ampül',
            'name_tu' => 'Ampuller',
            'name_en' => 'Bulbs',
            'name_ru' => 'Лампа',
        ], [
            'id' => '185',
            'parent_id' => '180',
            'name_az' => 'Gücləndirici çeviricilər',
            'name_tu' => 'Headlight',
            'name_en' => 'Headlight buckets',
            'name_ru' => 'Усилитель-преобразователь',
        ], [
            'id' => '186',
            'parent_id' => '180',
            'name_az' => 'Əsas kordonlar',
            'name_tu' => 'Gerekli kablolar',
            'name_en' => 'Necessary cords',
            'name_ru' => 'Кабель для авто',
        ], [
            'id' => '187',
            'parent_id' => '180',
            'name_az' => 'Məftillər',
            'name_tu' => 'Teller',
            'name_en' => 'Wires',
            'name_ru' => 'Автомобильные провода',
        ], [
            'id' => '188',
            'parent_id' => '180',
            'name_az' => 'Bağlayıcılar',
            'name_tu' => 'Konektörler',
            'name_en' => 'Connectors',
            'name_ru' => 'Автомобильные разъемы',
        ], [
            'id' => '189',
            'parent_id' => '180',
            'name_az' => 'Quraşdırma avadanlığı',
            'name_tu' => 'Kurulum ekipmanı',
            'name_en' => 'Installation equipment',
            'name_ru' => 'Монтажное оборудование ',
        ], [
            'id' => '190',
            'parent_id' => '180',
            'name_az' => 'Rezindən avtomobil döşəkçələri',
            'name_tu' => 'Kauçuk araba paspasları',
            'name_en' => 'Rubber car mats',
            'name_ru' => 'резиновые коврики',
        ], [
            'id' => '191',
            'parent_id' => '180',
            'name_az' => 'Süni toxuculuq materiallarından hazırlanmış a',
            'name_tu' => 'İnsan yapımı tekstil malzemelerinden araba paspasları',
            'name_en' => 'Car mats of man-made textile materials',
            'name_ru' => 'Коврики из искусственных текстильных материал',
        ], [
            'id' => '192',
            'parent_id' => '180',
            'name_az' => 'Güzgülər',
            'name_tu' => 'Aynalar',
            'name_en' => 'Mirrors',
            'name_ru' => 'Автомобильные зеркала',
        ], [
            'id' => '193',
            'parent_id' => '180',
            'name_az' => 'Nasoslar və Filtrlər',
            'name_tu' => 'Pompalar ve filtreler',
            'name_en' => 'Pumps and filters',
            'name_ru' => 'Фильтры, насосы',
        ], [
            'id' => '194',
            'parent_id' => '180',
            'name_az' => 'Hava filtrləri',
            'name_tu' => 'Hava filtreleri',
            'name_en' => 'Air filters',
            'name_ru' => 'воздушный фильтр ',
        ], [
            'id' => '195',
            'parent_id' => '180',
            'name_az' => 'Yağ və benzin filtrləri',
            'name_tu' => 'Yağ ve benzin filtreleri',
            'name_en' => 'Oil and gasoline filters',
            'name_ru' => 'Масляный и топливный фильтр ,',
        ], [
            'id' => '196',
            'parent_id' => null,
            'name_az' => 'Qida əlavələri,Dərman',
            'name_tu' => 'Besin takviyeleri',
            'name_en' => ' Food supplements',
            'name_ru' => 'Пищевые добавки',
        ], [
            'id' => '197',
            'parent_id' => '196',
            'name_az' => 'Zülal tozu',
            'name_tu' => 'Protein tozları',
            'name_en' => 'Protein powders',
            'name_ru' => 'Протеиновый порошок ',
        ], [
            'id' => '198',
            'parent_id' => '196',
            'name_az' => 'İçkilər',
            'name_tu' => 'İçecekler',
            'name_en' => 'Beverages',
            'name_ru' => 'спортивные напитки',
        ], [
            'id' => '199',
            'parent_id' => '196',
            'name_az' => 'Içki tozları',
            'name_tu' => 'İçecek tozları',
            'name_en' => 'Beverage powders',
            'name_ru' => 'Питьевой порошок ',
        ], [
            'id' => '200',
            'parent_id' => '196',
            'name_az' => 'Tərkibində kakao olan məhsullar',
            'name_tu' => 'Kakao içeren ürünler',
            'name_en' => 'Preparations containing cocoa',
            'name_ru' => 'пищевые продукты содержащие какао ',
        ], [
            'id' => '201',
            'parent_id' => '196',
            'name_az' => 'Zərdab',
            'name_tu' => 'Peynir suyu (protein takviyesi)',
            'name_en' => 'Whey',
            'name_ru' => 'Сыворотка (протеиновая добавка)',
        ], [
            'id' => '202',
            'parent_id' => null,
            'name_az' => 'Ev aksesuarları(mebel,dekor və digər)',
            'name_tu' => 'Ev aksesuarları (mobilya, dekor ve diğerleri',
            'name_en' => 'Home accessories (furniture, decor and others',
            'name_ru' => 'Аксессуары для дома(мебель,декор и др.)',
        ], [
            'id' => '203',
            'parent_id' => '202',
            'name_az' => 'Güzgü',
            'name_tu' => 'Aynalar',
            'name_en' => 'Mirrors',
            'name_ru' => 'зеркало',
        ], [
            'id' => '204',
            'parent_id' => '202',
            'name_az' => 'Yataq mebeli',
            'name_tu' => 'Yatak odası mobilyası',
            'name_en' => 'Bedroom furniture',
            'name_ru' => 'спальняя мебель',
        ], [
            'id' => '205',
            'parent_id' => '202',
            'name_az' => 'Qonaq mebeli',
            'name_tu' => 'Salon mobilyası',
            'name_en' => 'Living room furniture',
            'name_ru' => 'гостиная мебель',
        ], [
            'id' => '206',
            'parent_id' => '202',
            'name_az' => 'Mətbəx mebeli',
            'name_tu' => 'Mutfak mobilyası',
            'name_en' => 'Kitchen furniture',
            'name_ru' => 'кухонная мебель',
        ], [
            'id' => '207',
            'parent_id' => '202',
            'name_az' => 'Hamam akseusarları',
            'name_tu' => 'Banyo aksesuarları',
            'name_en' => 'Bathroom accessories',
            'name_ru' => 'ванные аксессуары',
        ], [
            'id' => '208',
            'parent_id' => '202',
            'name_az' => 'Divar kağızı',
            'name_tu' => 'Duvar kağıtları',
            'name_en' => 'Wallpapers',
            'name_ru' => 'обои',
        ], [
            'id' => '209',
            'parent_id' => '202',
            'name_az' => 'Saatlar',
            'name_tu' => 'Saatler',
            'name_en' => 'Clocks',
            'name_ru' => 'часы',
        ], [
            'id' => '210',
            'parent_id' => '202',
            'name_az' => 'Divar üçün tablo',
            'name_tu' => 'duvar için tablo',
            'name_en' => 'Wall painting',
            'name_ru' => 'настенная картина',
        ], [
            'id' => '211',
            'parent_id' => '202',
            'name_az' => 'Plastik mətbəx əşyaları',
            'name_tu' => 'Plastik mutfak eşyaları',
            'name_en' => 'Plastic kitchen utensils',
            'name_ru' => 'пластиковые принадлежности для кухни',
        ], [
            'id' => '212',
            'parent_id' => '202',
            'name_az' => 'Metaldan mətbəx əşyaları',
            'name_tu' => 'Metal mutfak eşyaları',
            'name_en' => 'Metal kitchen utensils',
            'name_ru' => 'принадлежности для кухни из металлов',
        ], [
            'id' => '213',
            'parent_id' => '202',
            'name_az' => 'Şüşədən mətbəx əşyaları',
            'name_tu' => 'Cam mutfak eşyaları',
            'name_en' => 'Glass kitchen utensils',
            'name_ru' => 'принадлежности для кухни из стекла',
        ], [
            'id' => '214',
            'parent_id' => null,
            'name_az' => 'İdman alətləri',
            'name_tu' => 'Spor malzemeleri',
            'name_en' => 'Sports equipment',
            'name_ru' => 'Спортивные принадлежности',
        ], [
            'id' => '215',
            'parent_id' => '214',
            'name_az' => 'Trenajor alətlər',
            'name_tu' => 'Egzersiz ekipmanları',
            'name_en' => 'Exercise equipment',
            'name_ru' => 'принадлежности для тренажеров',
        ], [
            'id' => '216',
            'parent_id' => '214',
            'name_az' => 'Toplar (futbol,voleybol, tennis,qolf və s. üç',
            'name_tu' => 'Toplar (futbol, ​​voleybol, tenis, golf vb.',
            'name_en' => 'Balls(footballl,volleyball, tennis,golf, etc.',
            'name_ru' => 'мячи(футбольные,войлебольные, теннисные,мяч д',
        ], [
            'id' => '217',
            'parent_id' => '214',
            'name_az' => 'Çantalar',
            'name_tu' => 'Çantalar',
            'name_en' => 'Bags',
            'name_ru' => 'сумки',
        ], [
            'id' => '218',
            'parent_id' => '214',
            'name_az' => 'İdmanda istifadə olunan yastıqcıqlar (dirsək,',
            'name_tu' => 'Sporda kullanılan yastıklar (dirsekler, dizler, kollar için)',
            'name_en' => 'Pillows used in sports (for elbows, knees, ch',
            'name_ru' => 'Подушки, используемые в спорте (для локтей, к',
        ], [
            'id' => '219',
            'parent_id' => '214',
            'name_az' => 'Baş-üz üçün qoruyucular (kaska, dəbilqə, başl',
            'name_tu' => 'Baş-yüz koruyucuları (kask, başlık vb.)',
            'name_en' => 'Head-face protectors (helmet,hood, etc)',
            'name_ru' => 'Защита головы (шлем, капюшон и т. Д.)',
        ], [
            'id' => '220',
            'parent_id' => '214',
            'name_az' => 'Əlcəklər',
            'name_tu' => 'Eldivenler',
            'name_en' => 'Gloves',
            'name_ru' => 'перчатки',
        ], [
            'id' => '221',
            'parent_id' => '214',
            'name_az' => 'Qoruyucu sarğılar (əl,ayaq,bilək, qol, diz və',
            'name_tu' => 'Koruyucu bandajlar (el, ayak, bilek, kol,',
            'name_en' => 'Protective bandages (hand, foot, wrist, arm,',
            'name_ru' => 'Защитные повязки (кисть, стопа, запястье, рук',
        ], [
            'id' => '222',
            'parent_id' => '214',
            'name_az' => 'Çubuqlar (qolf, xokkey və s.)',
            'name_tu' => 'Sopalar (golf, hokey vb.)',
            'name_en' => 'Sticks (golf, hockey, etc.)',
            'name_ru' => 'Клюшки (гольф, хоккей и др.)',
        ], [
            'id' => '223',
            'parent_id' => '214',
            'name_az' => 'Raketka (tennis,badminton və s.)',
            'name_tu' => 'Raket (tenis, badminton vb.)',
            'name_en' => 'Racket (tennis, badminton, etc.)',
            'name_ru' => 'ракетки (теннисные,для бадминтона и др.)',
        ], [
            'id' => '224',
            'parent_id' => '214',
            'name_az' => 'İdman üçün silahlar (paint ball, atıcılıq və',
            'name_tu' => 'Spor silahları (boya topu, atış vb.)',
            'name_en' => 'Weapons for sports (paint ball, shooting, etc',
            'name_ru' => 'Оружие для спорта (пейнтбол, стрелковое и др.',
        ], [
            'id' => '225',
            'parent_id' => '214',
            'name_az' => 'İdman silahları üçün toplar-güllələr (paint b',
            'name_tu' => 'Spor silahları için toplar (paint ball, shootin)',
            'name_en' => 'Balls for sports weapons (paint ball, shootin',
            'name_ru' => 'шары для спортивного оружия (пейнтбол, стрелк',
        ], [
            'id' => '226',
            'parent_id' => '214',
            'name_az' => 'Seqveylər və elektrik skuterlər',
            'name_tu' => 'Payetler ve elektrikli scooter',
            'name_en' => 'Sequins and electric scooters',
            'name_ru' => 'Segway и электро скутера',
        ], [
            'id' => '227',
            'parent_id' => '214',
            'name_az' => 'Diyircəkli konki, xizək,skateboard,snowboard',
            'name_tu' => 'Patenler, kızak, kaykay, snowboard, e',
            'name_en' => 'Roller skates, sledge,skateboard,snowboard, e',
            'name_ru' => 'Роликовые коньки, санки, скейтборд, сноуборд',
        ], [
            'id' => '228',
            'parent_id' => '214',
            'name_az' => 'Oxçuluq üçün ləvazimatlar',
            'name_tu' => 'Okçuluk ekipmanları',
            'name_en' => 'Archery equipments',
            'name_ru' => 'Снаряжение для стрельбы из лука',
        ], [
            'id' => '229',
            'parent_id' => '214',
            'name_az' => 'Gimnastika alətləri',
            'name_tu' => 'Jimnastik aletleri',
            'name_en' => 'Gymnastic instruments',
            'name_ru' => 'Снаряжение для гимнастики',
        ], [
            'id' => '230',
            'parent_id' => null,
            'name_az' => 'Kamera və hissələri',
            'name_tu' => 'Kamera ve parçalar',
            'name_en' => ' Camera and parts',
            'name_ru' => 'Камера и детали',
        ], [
            'id' => '231',
            'parent_id' => '230',
            'name_az' => 'Avtomobillər üçün kamera dəstləri (kamera, mo',
            'name_tu' => 'Arabalar için kamera setleri (kamera, monitör)',
            'name_en' => 'Camera sets for cars (camera, monitor)',
            'name_ru' => 'Комплекты виденаблюдения для автомобилей (кам',
        ], [
            'id' => '232',
            'parent_id' => '230',
            'name_az' => 'Video registratorlar',
            'name_tu' => 'Video kaydediciler',
            'name_en' => 'Video recorders',
            'name_ru' => 'видео регистратор',
        ], [
            'id' => '233',
            'parent_id' => '230',
            'name_az' => 'Video kameralar',
            'name_tu' => 'Video kameralar',
            'name_en' => 'Video cameras',
            'name_ru' => 'видео камера',
        ], [
            'id' => '234',
            'parent_id' => '230',
            'name_az' => 'Video nəzarət kameraları',
            'name_tu' => 'Video gözetim kameraları',
            'name_en' => 'Video surveillance cameras',
            'name_ru' => 'камеры видеонаблюдения',
        ], [
            'id' => '235',
            'parent_id' => '230',
            'name_az' => 'DVR',
            'name_tu' => 'DVR',
            'name_en' => 'DVR',
            'name_ru' => 'видеорегистратор DVR',
        ], [
            'id' => '236',
            'parent_id' => '230',
            'name_az' => 'Rəqəmsal kameralar (foto aparatlar)',
            'name_tu' => 'Dijital kameralar',
            'name_en' => 'Digital cameras',
            'name_ru' => 'цифровые камеры (фото аппарат)',
        ], [
            'id' => '237',
            'parent_id' => '230',
            'name_az' => 'Veb kameralar',
            'name_tu' => 'Web kameraları',
            'name_en' => 'Webcams',
            'name_ru' => 'Веб-камера',
        ], [
            'id' => '238',
            'parent_id' => '230',
            'name_az' => 'Obyektiv linzalar',
            'name_tu' => 'Objektif lensler',
            'name_en' => 'Objective lenses',
            'name_ru' => 'Объективные линзы',
        ], [
            'id' => '239',
            'parent_id' => '230',
            'name_az' => 'Selfie çubuqları, monopodlar, bipodlar, tripo',
            'name_tu' => 'Selfie çubukları, monopodlar, iki ayaklılar, tripodlar',
            'name_en' => 'Selfie sticks, monopods, bipods, tripods',
            'name_ru' => 'Селфи палка,штатив, монопод,сошки',
        ], [
            'id' => '430',
            'parent_id' => '230',
            'name_az' => 'Kameralar üçün yaddaş kartları və flash kartl',
            'name_tu' => 'Kameralar için hafıza kartları ve flash kartlar',
            'name_en' => 'Memory cards and flash cards for cameras',
            'name_ru' => 'Карты памяти и флеш карты для камер',
        ], [
            'id' => '431',
            'parent_id' => null,
            'name_az' => 'Kitablar',
            'name_tu' => 'Kitabın',
            'name_en' => ' Books',
            'name_ru' => 'Книги',
        ], [
            'id' => '432',
            'parent_id' => '431',
            'name_az' => 'Kitab',
            'name_tu' => 'Kitap',
            'name_en' => 'Book',
            'name_ru' => 'книга',
        ], [
            'id' => '433',
            'parent_id' => '431',
            'name_az' => 'Jurnal',
            'name_tu' => 'Dergi',
            'name_en' => 'Magazine',
            'name_ru' => 'журнал',
        ], [
            'id' => '434',
            'parent_id' => '431',
            'name_az' => 'Elektron kitab',
            'name_tu' => 'Elektronik kitap',
            'name_en' => 'Electronic book',
            'name_ru' => 'электронная книга',
        ], [
            'id' => '435',
            'parent_id' => '431',
            'name_az' => 'Audio kitab',
            'name_tu' => 'Sesli kitap',
            'name_en' => 'Audio book',
            'name_ru' => 'аудиокнига',
        ], [
            'id' => '436',
            'parent_id' => '431',
            'name_az' => 'Film və musiqi diski',
            'name_tu' => 'Film ve müzik diski',
            'name_en' => 'Movie and music disc',
            'name_ru' => 'Компакт-диск ',
        ], [
            'id' => '437',
            'parent_id' => '431',
            'name_az' => 'Səsyazıları toplusu',
            'name_tu' => 'Kayıtların toplanması',
            'name_en' => 'Collection of recordings',
            'name_ru' => 'Сборник записей (цифровая книга)',
        ], [
            'id' => '438',
            'parent_id' => '431',
            'name_az' => 'Elektron kitab oxuyucu',
            'name_tu' => 'Elektronik kitap okuyucusu',
            'name_en' => 'E-book reader',
            'name_ru' => 'электронная книга ( E-book reader)',
        ], [
            'id' => '439',
            'parent_id' => '133',
            'name_az' => 'Telefon ehtiyat hissələri',
            'name_tu' => 'Telefon yedek parçaları',
            'name_en' => 'Phone spare parts',
            'name_ru' => 'Запчасти для телефонов',
        ], [
            'id' => '440',
            'parent_id' => '196',
            'name_az' => 'Dərman',
            'name_tu' => 'ilaç',
            'name_en' => 'medicine',
            'name_ru' => 'лекарство',
        ], [
            'id' => '441',
            'parent_id' => null,
            'name_az' => 'Kimyəvi təmizləyici vasitələr',
            'name_tu' => 'Temizlik Deterjanları',
            'name_en' => 'Cleaning Detergents',
            'name_ru' => 'Моющие средства',
        ], [
            'id' => '442',
            'parent_id' => '441',
            'name_az' => 'Qabyuma vasitələri',
            'name_tu' => 'Bulaşık deterjanı',
            'name_en' => 'Dishwashing liquid',
            'name_ru' => 'Моющие средства для посуды',
        ], [
            'id' => '443',
            'parent_id' => '441',
            'name_az' => 'Paltaryuma vasitələri',
            'name_tu' => 'Çamaşır deterjanları,',
            'name_en' => 'laundry detergents,',
            'name_ru' => 'Моющие средства для стирки',
        ], [
            'id' => '444',
            'parent_id' => '441',
            'name_az' => 'Avtomobil təmizləmə vasitələri',
            'name_tu' => 'araba yıkama sıvı deterjanları',
            'name_en' => 'carwash liquid detergents',
            'name_ru' => 'Моющие средства для автомойки',
        ], [
            'id' => '445',
            'parent_id' => '441',
            'name_az' => 'Mebel təmizləmə vasitələri',
            'name_tu' => 'mobilya temizleme deterjanları',
            'name_en' => 'furniture cleaning detergents',
            'name_ru' => 'Чистящие средства для мебели',
        ], [
            'id' => '446',
            'parent_id' => '441',
            'name_az' => 'Digər vasitələr',
            'name_tu' => 'diğer deterjanlar',
            'name_en' => 'other detergents',
            'name_ru' => 'Другие моющие средства',
        ], [
            'id' => '447',
            'parent_id' => null,
            'name_az' => 'Suvinir və oyuncaqlar',
            'name_tu' => 'Hatıralık eşyalar ve oyuncaklar',
            'name_en' => 'Souvenirs and toys',
            'name_ru' => 'asfas',
        ], [
            'id' => '448',
            'parent_id' => '447',
            'name_az' => 'Suvinirlər',
            'name_tu' => 'Hediyelik eşya',
            'name_en' => 'Souvenirs',
            'name_ru' => 'Сувениры',
        ], [
            'id' => '449',
            'parent_id' => '447',
            'name_az' => 'Oyuncaqlar',
            'name_tu' => 'Oyuncaklar',
            'name_en' => 'Toys',
            'name_ru' => 'Игрушки',
        ], [
            'id' => '450',
            'parent_id' => null,
            'name_az' => 'Təmir-tikinti alətləri',
            'name_tu' => 'Onarım ve İnşaat araçları',
            'name_en' => 'Repair and Construction tools',
            'name_ru' => 'Ремонтно- Строительные инструменты',
        ], [
            'id' => '451',
            'parent_id' => '450',
            'name_az' => 'Əl alətləri, alət dəstləri',
            'name_tu' => 'el aletleri (manuel), Alet setleri',
            'name_en' => 'handheld tools (manual), Tool sets',
            'name_ru' => 'Ручные инструменты, Наборы инструментов',
        ], [
            'id' => '452',
            'parent_id' => '450',
            'name_az' => 'Elektrikli əl alətləri',
            'name_tu' => 'Elektrikli el aletleri',
            'name_en' => 'Electric hand tools',
            'name_ru' => 'Ручные электрические инструменты',
        ], [
            'id' => '453',
            'parent_id' => '450',
            'name_az' => 'Digər',
            'name_tu' => 'diğerleri',
            'name_en' => 'others',
            'name_ru' => 'Другие',
        ], [
            'id' => '454',
            'parent_id' => null,
            'name_az' => 'Ovçuluq ləvazimatları',
            'name_tu' => 'Avcılık ekipmanları',
            'name_en' => 'Hunting equipment',
            'name_ru' => 'Охотничье снаряжение',
        ], [
            'id' => '455',
            'parent_id' => '454',
            'name_az' => 'Balıqtutma vasitələri',
            'name_tu' => 'balıkçılık ekipmanları',
            'name_en' => 'fishing equipment',
            'name_ru' => 'Рыболовное снаряжение',
        ], [
            'id' => '456',
            'parent_id' => '454',
            'name_az' => 'Digər',
            'name_tu' => 'others',
            'name_en' => 'others',
            'name_ru' => 'Другие',
        ], [
            'id' => '457',
            'parent_id' => '137',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '458',
            'parent_id' => '146',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '459',
            'parent_id' => '110',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '460',
            'parent_id' => '92',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '461',
            'parent_id' => '116',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '462',
            'parent_id' => '133',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '463',
            'parent_id' => '202',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '464',
            'parent_id' => '230',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '465',
            'parent_id' => '441',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '466',
            'parent_id' => '447',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '468',
            'parent_id' => '454',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '469',
            'parent_id' => '159',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '470',
            'parent_id' => '431',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '471',
            'parent_id' => '1',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '472',
            'parent_id' => '39',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '473',
            'parent_id' => '52',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '474',
            'parent_id' => '66',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '475',
            'parent_id' => '180',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '476',
            'parent_id' => '196',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '477',
            'parent_id' => '214',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '478',
            'parent_id' => '78',
            'name_az' => 'Digər',
            'name_tu' => 'Others',
            'name_en' => 'Others',
            'name_ru' => 'Другие',
        ], [
            'id' => '479',
            'parent_id' => '92',
            'name_az' => 'Klaviatura',
            'name_tu' => 'Klavye',
            'name_en' => 'Keyboard',
            'name_ru' => 'Клавиатурa',
        ], [
            'id' => '480',
            'parent_id' => '92',
            'name_az' => 'Ana kart',
            'name_tu' => 'Ana plata',
            'name_en' => 'Mother board',
            'name_ru' => 'Материнские плата',
        ], [
            'id' => '481',
            'parent_id' => '92',
            'name_az' => 'Kompüterlərin digər hissələri və aksesuarları',
            'name_tu' => 'Bilgisayarların diğer parçaları ve aksesuarları (',
            'name_en' => 'Other parts and accessories of computers (not',
            'name_ru' => 'Прочие части и аксессуары компьютеров (кроме',
        ], [
            'id' => '482',
            'parent_id' => '110',
            'name_az' => 'Oyun kontolerləri',
            'name_tu' => 'Oyun kontrolörleri (direksiyon ve pedal kombinasyonu',
            'name_en' => 'Game controllers (steering and pedal combinat',
            'name_ru' => 'Игровые контроллеры (комбинации рулевого упра',
        ], [
            'id' => '486',
            'parent_id' => '116',
            'name_az' => 'Üz üçün tozlar (Kirşan, Tonal krem və s.)',
            'name_tu' => 'Tozlar (Fondöten kremi, Allık vb.)',
            'name_en' => 'Powders (Foundation cream, Blushes etc.)',
            'name_ru' => 'пудры (тональный крем,румяна и т.д )',
        ], [
            'id' => '487',
            'parent_id' => '116',
            'name_az' => 'Tuş, göz kölgələri, göz layneri, göz qaş məhs',
            'name_tu' => 'Maskaralar, göz farı, göz gömlekleri, kaş p',
            'name_en' => 'Mascaras, eye shadows, eye liners, eye brow p',
            'name_ru' => 'Туши, тени, подводки для глаз, средства для б',
        ], [
            'id' => '488',
            'parent_id' => '116',
            'name_az' => 'Dodaq boyası( Pomada), dodaq parıldadıcısı və',
            'name_tu' => 'Ruj, dudak parlatıcısı ve diğer dudak makyajı',
            'name_en' => 'Lipstick, lip gloss and other lip make-up',
            'name_ru' => 'Губная помада, блеск для губ и другой макияж',
        ], [
            'id' => '489',
            'parent_id' => '116',
            'name_az' => 'Dırnaq lakı, manikür və pedikür hazırlıqları',
            'name_tu' => 'Tırnak cilası, manikür ve pedikür preparatı',
            'name_en' => 'Nail varnish, manicure and pedicure preparati',
            'name_ru' => 'Лак для ногтей, средства для маникюра и педик',
        ], [
            'id' => '490',
            'parent_id' => '116',
            'name_az' => 'Ətirlər, tualet suyu - məhsullar',
            'name_tu' => 'Parfümler, eau de toilette -products',
            'name_en' => 'Perfumes, eau de toilette -products',
            'name_ru' => 'Духи, туалетная вода, товары',
        ], [
            'id' => '491',
            'parent_id' => '116',
            'name_az' => 'Nəmləndiricilər və digər dəri məhsulları, gün',
            'name_tu' => 'Nemlendiriciler ve diğer cilt ürünleri, güneş kremi',
            'name_en' => 'Moisturizers and other skin products, sunscre',
            'name_ru' => 'Увлажняющие средства и другие продукты для ко',
        ], [
            'id' => '492',
            'parent_id' => '116',
            'name_az' => 'Dezodorantlar və antiperspirantlar',
            'name_tu' => 'Deodorantlar ve antiperspiranlar',
            'name_en' => 'Deodorants and antiperspirants',
            'name_ru' => 'Дезодоранты и антиперспиранты',
        ], [
            'id' => '493',
            'parent_id' => '116',
            'name_az' => 'Vanna yağları, hamam duzları və digər hamam h',
            'name_tu' => 'Banyo yağları, banyo tuzları ve diğer banyo preparatları',
            'name_en' => 'Bath oils, bath salts and other bath preparat',
            'name_ru' => 'Масла для ванн, соли для ванн и другие средст',
        ], [
            'id' => '494',
            'parent_id' => '116',
            'name_az' => '',
            'name_tu' => 'Duş Jeli',
            'name_en' => 'Liquid shower wash',
            'name_ru' => 'Жидкий гель для душа',
        ], [
            'id' => '495',
            'parent_id' => '116',
            'name_az' => 'Diş ipi',
            'name_tu' => 'Diş ipi',
            'name_en' => 'Dental floss',
            'name_ru' => 'Зубная нить',
        ], [
            'id' => '496',
            'parent_id' => '116',
            'name_az' => 'Diş fırçaları',
            'name_tu' => 'Diş fırçaları',
            'name_en' => 'Toothbrushes',
            'name_ru' => 'Зубные щетки',
        ], [
            'id' => '497',
            'parent_id' => '116',
            'name_az' => 'Diş pastası və ağız yuyucusu',
            'name_tu' => 'Diş macunu ve gargara',
            'name_en' => 'Toothpaste and mouthwash',
            'name_ru' => 'Зубная паста и жидкость для полоскания рта',
        ], [
            'id' => '498',
            'parent_id' => '116',
            'name_az' => 'Diş ağartma məhsulları',
            'name_tu' => 'Diş beyazlatma ürünleri',
            'name_en' => 'Tooth whitening products',
            'name_ru' => 'Средства для отбеливания зубов',
        ], [
            'id' => '499',
            'parent_id' => '116',
            'name_az' => 'Saç üslubu məhsulları, saç boyası və digər sa',
            'name_tu' => 'Saç şekillendirme ürünleri, saç boyası ve diğer hai',
            'name_en' => 'Hair styling products, hair dye and other hai',
            'name_ru' => 'Средства для укладки, краски для волос и друг',
        ], [
            'id' => '500',
            'parent_id' => '116',
            'name_az' => 'Şampunlar, kondisionerlər və saç yağları',
            'name_tu' => 'Şampuanlar, saç kremleri ve saç yağları',
            'name_en' => 'Shampoos, conditioners and hair oils',
            'name_ru' => 'Шампуни, кондиционеры и масла для волос',
        ], [
            'id' => '501',
            'parent_id' => '116',
            'name_az' => 'Peruklar və insan saçlarından hazırlanmış dig',
            'name_tu' => 'İnsandan yapılmış peruklar ve diğer saç uzatma',
            'name_en' => 'Wigs and other hair extensions made of human',
            'name_ru' => 'Парики и другие изделия для наращивания волос',
        ], [
            'id' => '502',
            'parent_id' => '116',
            'name_az' => 'Fırçalar, saç fırçaları və təraş fırçaları',
            'name_tu' => 'Makyaj fırçaları, saç fırçaları ve tıraş fırçası',
            'name_en' => 'Make up brushes, hairbrushes and shaving brus',
            'name_ru' => 'Кисти для макияжа, расчески и кисти для брить',
        ], [
            'id' => '503',
            'parent_id' => '159',
            'name_az' => 'Üzqırxanlar, saç kəsmə maşınları və epilyasiy',
            'name_tu' => 'Tıraş makineleri, saç kesme makineleri ve tüy alma aparatı',
            'name_en' => 'Shavers, hair clippers and hair-removing appl',
            'name_ru' => 'Бритвы, машинки для стрижки и эпиляции (элект',
        ], [
            'id' => '504',
            'parent_id' => '196',
            'name_az' => 'Çay',
            'name_tu' => 'Çay',
            'name_en' => 'Çay',
            'name_ru' => 'Чай',
        ], [
            'id' => '505',
            'parent_id' => '196',
            'name_az' => 'Qəhvə',
            'name_tu' => 'Kahve',
            'name_en' => 'Coffee',
            'name_ru' => 'Кофе',
        ], [
            'id' => '507',
            'parent_id' => '450',
            'name_az' => 'Soket dəstləri',
            'name_tu' => 'Soket setleri',
            'name_en' => 'Socket sets',
            'name_ru' => 'Наборы розеток',
        ], [
            'id' => '508',
            'parent_id' => '454',
            'name_az' => 'Çadırlar',
            'name_tu' => 'Çadırlar',
            'name_en' => 'Tents',
            'name_ru' => 'Палатки',
        ], [
            'id' => '509',
            'parent_id' => '454',
            'name_az' => 'Yuxu çantaları',
            'name_tu' => 'Uyku tulumları',
            'name_en' => 'Sleeping bags',
            'name_ru' => 'Спальные мешки',
        ], [
            'id' => '510',
            'parent_id' => '454',
            'name_az' => 'Ov tüfənglərinin və tüfənglərin hissələri',
            'name_tu' => 'Av tüfeği ve tüfek parçaları',
            'name_en' => 'Parts of shotguns and rifles',
            'name_ru' => 'Части ружей и винтовок',
        ], [
            'id' => '511',
            'parent_id' => null,
            'name_az' => 'Ampullər, lampalar',
            'name_tu' => 'Ampuller, lambalar',
            'name_en' => 'Bulbs, lamps',
            'name_ru' => 'лампы',
        ], [
            'id' => '512',
            'parent_id' => '511',
            'name_az' => 'Tavan, divar, standart və masa lampaları',
            'name_tu' => 'Tavan, duvar, standart ve masa lambaları',
            'name_en' => 'Ceiling, wall, standard and table lamps',
            'name_ru' => 'Потолочные, настенные, торшеры и настольные л',
        ], [
            'id' => '513',
            'parent_id' => '511',
            'name_az' => 'LED lampalar (parıltı lampalarını əvəz edir)',
            'name_tu' => 'LED ampuller (kızdırma ampullerinin yerini alır) ve LED lambalar',
            'name_en' => 'LED bulbs (replaces glow bulbs) and LED lamps',
            'name_ru' => 'Светодиодные лампы (заменяет лампы накаливани',
        ], [
            'id' => '514',
            'parent_id' => '511',
            'name_az' => 'Nəqliyyat vasitələri üçün lampalar (parıltı f',
            'name_tu' => 'Araçlar için ampuller (kızdırma filamanı)',
            'name_en' => 'Bulbs for vehicles (glow filament)',
            'name_ru' => 'Лампы для автомобилей (нить накаливания)',
        ], [
            'id' => '515',
            'parent_id' => '511',
            'name_az' => 'Nəqliyyat vasitələri üçün lampalar (Volfram h',
            'name_tu' => 'Araçlar için ampuller (Tungsten halojen) H1, H4,',
            'name_en' => 'Bulbs for vehicles (Tungsten halogen) H1, H4,',
            'name_ru' => 'Лампы для автомобилей (галогенные вольфрамовы',
        ], [
            'id' => '516',
            'parent_id' => '511',
            'name_az' => 'Nəqliyyat vasitələri üçün lampalar (xenon)',
            'name_tu' => 'Araçlar için ampuller (xenon)',
            'name_en' => 'Bulbs for vehicles (xenon)',
            'name_ru' => 'Лампочки для автомобилей (ксенон)',
        ], [
            'id' => '517',
            'parent_id' => null,
            'name_az' => 'Ofis ləvazimatları və kağız məhsulları',
            'name_tu' => 'El işleri ve kağıt ürünleri',
            'name_en' => 'Crafts and paper products',
            'name_ru' => 'Ремесла и изделия из бумаги',
        ], [
            'id' => '518',
            'parent_id' => '517',
            'name_az' => 'Kartpostallar çap edilmişdir',
            'name_tu' => 'Basılı kartpostallar',
            'name_en' => 'Printed postcards',
            'name_ru' => 'Открытки печатные',
        ], [
            'id' => '519',
            'parent_id' => '517',
            'name_az' => 'Təqvimlər',
            'name_tu' => 'Takvimler',
            'name_en' => 'Calendars',
            'name_ru' => 'Календари',
        ], [
            'id' => '520',
            'parent_id' => '517',
            'name_az' => 'Qələm, marker, karandaş və rəsm boyaları',
            'name_tu' => 'Kalemler, işaretleme kalemleri, kurşun kalem uçları ve çizim c',
            'name_en' => 'Pens, marker pens, pencil leads and drawing c',
            'name_ru' => 'Ручки, маркеры, грифели для карандашей и угол',
        ], [
            'id' => '521',
            'parent_id' => '517',
            'name_az' => 'Qayçı',
            'name_tu' => 'Makas',
            'name_en' => 'Scissors',
            'name_ru' => 'Ножницы',
        ], [
            'id' => '524',
            'parent_id' => null,
            'name_az' => 'Heyvan təchizatı',
            'name_tu' => 'Evcil Hayvan malzemeleri',
            'name_en' => 'Pet supplies',
            'name_ru' => 'Зоотовары',
        ], [
            'id' => '525',
            'parent_id' => '524',
            'name_az' => 'Heyvan ləvazimatları (qurğuşun və qoşqu, it p',
            'name_tu' => 'Evcil hayvan malzemeleri (kablolar ve koşum takımları, köpek paltoları,',
            'name_en' => 'Pet supplies (leads and harnesses, dog coats,',
            'name_ru' => 'Принадлежности для домашних животных (поводки',
        ], [
            'id' => '526',
            'parent_id' => '524',
            'name_az' => 'İtlər üçün naviqasiya yaxası',
            'name_tu' => 'Köpekler için navigasyon tasması',
            'name_en' => 'Navigation collar for dogs',
            'name_ru' => 'Навигационный ошейник для собак',
        ], [
            'id' => '527',
            'parent_id' => '524',
            'name_az' => 'Heyvan oyuncaqları, rezin',
            'name_tu' => 'Evcil hayvan oyuncakları, kauçuk',
            'name_en' => 'Pet toys, rubber',
            'name_ru' => 'Игрушки домашних животных, резина',
        ], [
            'id' => '528',
            'parent_id' => '524',
            'name_az' => 'Simli və ipli heyvan oyuncaqları və pişik ağa',
            'name_tu' => 'Evcil hayvan oyuncakları ve kedi ağaçları, ip ve ipten',
            'name_en' => 'Pet toys and cat trees, of string and rop',
            'name_ru' => 'Игрушки домашних животных и кошачьи елки из в',
        ], [
            'id' => '529',
            'parent_id' => null,
            'name_az' => 'Süfrə və mətbəx əşyaları',
            'name_tu' => 'Sofra ve mutfak gereçleri',
            'name_en' => 'Tableware and kitchenware',
            'name_ru' => 'Посуда и кухонные принадлежности',
        ], [
            'id' => '530',
            'parent_id' => '529',
            'name_az' => 'Plastik süfrə və mətbəx əşyaları da birdəfəli',
            'name_tu' => 'Plastik süfrə və mətbəx əşyaları da birdəfəli',
            'name_en' => 'Plastik süfrə və mətbəx əşyaları da birdəfəli',
            'name_ru' => 'Пластиковая посуда и кухонные принадлежности,',
        ], [
            'id' => '531',
            'parent_id' => '529',
            'name_az' => 'Taxta süfrə və ya mətbəx əşyaları',
            'name_tu' => 'Ahşap sofra veya mutfak gereçleri',
            'name_en' => 'Wooden tableware or kitchenware',
            'name_ru' => 'Деревянная посуда или кухонные принадлежности',
        ], [
            'id' => '532',
            'parent_id' => '529',
            'name_az' => 'Adi dulusçuluq qabları və mətbəx əşyaları',
            'name_tu' => 'Sıradan çanak çömleklerden sofra ve mutfak gereçleri',
            'name_en' => 'Tableware and kitchenware of common pottery',
            'name_ru' => 'Посуда и посуда из обычной керамики',
        ], [
            'id' => '533',
            'parent_id' => '529',
            'name_az' => 'Seramik süfrə və ya mətbəx ləvazimatları',
            'name_tu' => 'Seramik sofra veya mutfak gereçleri',
            'name_en' => 'Ceramic tableware or kitchenware',
            'name_ru' => 'Керамическая посуда или кухонные принадлежнос',
        ], [
            'id' => '534',
            'parent_id' => '529',
            'name_az' => 'Porselen və ya çini süfrə və ya ev əşyaları',
            'name_tu' => 'Porselen veya çiniden sofra veya mutfak eşyaları',
            'name_en' => 'Tableware or kitcheware of porcelain or china',
            'name_ru' => 'Посуда или кухонные принадлежности из фарфора',
        ], [
            'id' => '535',
            'parent_id' => '529',
            'name_az' => 'Masa və ya mətbəx üçün istifadə olunan şüşə q',
            'name_tu' => 'Masa veya mutfak için kullanılan cam eşyalar',
            'name_en' => 'Glassware used for table or kitchen',
            'name_ru' => 'Стеклянная посуда используется для стола или',
        ], [
            'id' => '536',
            'parent_id' => '529',
            'name_az' => 'Masa örtükləri və peçetələr',
            'name_tu' => 'Kağıt masa örtüleri ve peçeteler',
            'name_en' => 'Tablecloths and serviettes of paper',
            'name_ru' => 'Скатерти и салфетки из бумаги',
        ], [
            'id' => '537',
            'parent_id' => '529',
            'name_az' => 'Mətbəx bıçaqları, masa  bıçaqları',
            'name_tu' => 'Mutfak bıçakları, Masa bıçakları',
            'name_en' => 'Kitchen knives, Table knives',
            'name_ru' => 'Ножи кухонные,  Столовые ножи',
        ], [
            'id' => '538',
            'parent_id' => '529',
            'name_az' => 'Qazan, tava',
            'name_tu' => 'Kazan, tava',
            'name_en' => '',
            'name_ru' => '',
        ]
    ];


    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach (self::ProductCategories as $productCategory) {
            ProductCategory::query()->firstOrCreate(
                [
                    'id' => $productCategory['id']
                ],
                [
                    'parent_id' => $productCategory['parent_id'],
                    'name_az' => $productCategory['name_az'],
                    'name_tu' => $productCategory['name_tu'],
                    'name_en' => $productCategory['name_en'],
                    'name_ru' => $productCategory['name_ru'],
                ]
            );
        }
    }
}
