<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TranslateSeeder extends Seeder
{
    public function __construct()
    {
        $this->groups = [
            'website' => $this->website_items,
            'member' => $this->member_items,
            'admin' => [],
        ];
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->groups as $list => $group) {
            foreach ($group as $key => $item) {
                DB::table('ltm_translations')->updateOrInsert(
                    [
                        'locale' => $this->locale,
                        'group' => $list,
                        'key' => $key,
                        'value' => $item,
                    ],
                    [
                        'key' => $key,
                        'value' => $item,
                        'locale' => $this->locale,
                        'group' => $list,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                );
            }
        }
    }


    private $locale = "en";

    private $member_items = [
        'login' => 'Login',
        'email' => 'Email',
        'password' => 'Password',
        'rememberme' => 'remember me',
        'name' => 'Name',
        'family' => 'Family',
        'passwordconfirmation' => 'Password Confirmation',
        'serialnumber' => 'Serial Number',
        'citizenship' => 'Citizenship',
        'phone' => 'phone',
        'birthday' => 'birthday',
        'address' => 'address',
        'gender' => 'gender',
        'male' => 'male',
        'female' => 'female',
        'Agreepolicy' => 'Agree the Terms and policy',
        'register' => 'Register',
        'all' => 'All',
        'ordered' => 'Ordered',
        'anbar' => 'anbar',
        'Heisway' => 'He is on his way',
        'Customsinspection' => 'Customs inspection',
        'warehouse' => 'warehouse',
        'courierdelivery' => 'Courier delivery',
        'return' => 'Return',
        'complete' => 'Complete',
        'order№' => 'Order №',
        'orderdate' => 'Order date',
        'shop' => 'Shop',
        'status' => 'Status',
        'action' => 'Action',
        'dashboard' => 'Dashboard',
        'myaddressesabroad' => 'My addresses abroad',
        'orders' => 'Orders',
        'mybindings' => 'My bindings',
        'aznBalance' => 'AZN Balance',
        'tlBalance' => 'TL Balance',
        'courier' => 'Courier',
        'inquiry' => 'Inquiry',
        'setting' => 'Setting',
        'logout' => 'Log Out',
        'customercode' => 'customer code',
        'invoice' => 'invoice',
        'order' => 'order',
        'filter' => 'Filter',
        'warehoseabroad' => 'WAREHOUSE ABROAD',
        'onway' => 'ON WAY',
        'custominspection' => 'CUSTOMS INSPECTION',
        'inwarehose' => 'IN WAREHOUSE',
        'orderid' => 'Order id',
        'link' => 'link',
        'price' => 'price',
        'hascargo' => 'has cargo',
        'cargo' => 'cargo',
        'quantity' => 'quantity',
        'description' => 'description',
        'specification' => 'specification',
        'show' => 'show',
        'cargointurkey' => 'Cargo in Turkey',
        'amountofcargo' => 'The amount of cargo',
        'total' => 'Total',
        'number' => 'Number',
        'measure' => 'Measure',
        'deletelink' => 'Delete link',
        'tooltipdesc' => 'This is the amount you paid for the product cost and delivery fee for the parcels you brought to the country in the last 30 days through Kargo.az. It should be noted that according to the legislation, the customs duty is applied when the cost of mail delivered for personal use within 30 days and the delivery fee paid for it exceeds a total of $ 300.',
        'lastdays' => 'Last 30 days',
        'paymentcard' => 'Payment by card',
        'paymentcarddesc' => 'You can pay with any credit or debit card',
        'paymenttlbalance' => 'Payment with TL balance',
        'paymenttlbalancedsc' => 'If you have enough funds in your TL balance, you can pay',
        'yourtlbalance' => 'Your TL balance',
        'deliveryoffice' => 'Delivery office',
        'makepayment' => 'Make a payment',
        'noitnot' => 'No, its not',
        'theamountcargo' => 'The amount of cargo',
        'addanewlink' => 'Add a new link',
        'dateofordering' => 'Date of ordering',
        'send' => 'Send',
        'attention' => 'Attention',
        'attentiondesc' => 'Dear customers, when you place your orders yourself, the declaration must be attached by you. It is not possible to add a declaration without downloading invoices. Accurate and prompt completion of the declaration will help your parcels to pass customs inspection faster and without problems.',
        'mybalance' => 'My balance',
        'lastaddeddate' => 'Last added date',
        'lastaddeddatedesc' => 'Increase your balance to pay for delivery to Azerbaijan and order an online courier
                        you can.',
        'lastaddeddatedesc1' => 'THE INCREASED BALANCE IS NOT RETURNED.',
        'balanceincreasepayment' => 'BALANCE INCREASE FOR PAYMENT',
        'balanceincreases' => 'The balance increases',
        'min' => 'min',
        'max' => 'max',
        'balanceincreasesdesc' => 'Increase your balance over the National Front',
        'accountnumber' => 'Account number',
        'accountnumberdesc1' => 'You approach the MilliÖN terminal, enter the "Delivery Service" section and switch to the "kargo.az" section. To pay for transportation and courier service, select "kargo.az AZN". In the drop-down box, dial your account number above and click "Continue". Enter and confirm the amount required for delivery and courier service. After completing the transaction, the amount will immediately appear in your balance in your personal account on kargo.az.',
        'accountnumberdesc2' => 'Note: It is not possible to make purchases in Turkey with the delivery balance! Money transfer from AZN balance to TRY balance is not possible!',
        'expenditure' => 'Expenditure',
        'income' => 'Income',
        'history' => 'History',
        'amount' => 'Amount',
        'operation' => 'Operation',
        'increasebalance' => 'Increase balance',
        'orderpayment' => 'Order Payment',
        'card' => 'Card',
        'balance' => 'Balance',
        'accept' => 'Accept',
        'message' => 'message',
        'deliveryonlinecourier' => 'You can top up your balance to pay for delivery to Azerbaijan and order an online courier.',
        'increasenotreturned' => 'THE INCREASED BALANCE IS NOT RETURNED.',
        'amountyoupaiddelivery' => 'This is the amount you paid for the product cost and delivery fee for the parcels you brought to the country in the last 30 days through Kargo.az. It should be noted that according to the legislation, the customs duty is applied when the cost of mail delivered for personal use within 30 days and the delivery fee paid for it exceeds a total of $ 300.',
        'last30days' => 'Last 30 days',
        'type' => 'type',
        'refid' => 'refid',
        'date' => 'refid',
        'profileinformation' => 'Profile Information',
        'other' => 'Other',
        'baku' => 'Baku',
        'ganja' => 'Ganja',
        'sumgayit' => 'Sumgayit',
        'zaqatala' => 'Zaqatala',
        'birthdate' => 'Birthdate',
        'save' => 'Save',
        'currentpassword' => 'Current Password',
        'enternewpassword' => 'Enter The New Password',
        'carefuladdingnewpassword!' => 'Be careful when adding a new password!',
        'usecharacterspassword' => 'Use characters in your password',
        'capitallettersyourpassword' => 'Use capital letters in your password',
        'usenumberinpassword' => 'Use a number in your password',
        'serialNumber' => 'Serial Number',
        'fin' => 'FIN',
        'user' => 'USER',
        'panel' => 'Panel',
        'exchangeratecalculator' => 'Exchange Rate Calculator',
        'select' => 'select',
        'calculate' => 'Calculate',
        'calculateexchange' => 'Calculated according to the exchange rate of the day.',
        'dailysize' => 'Daily size',
    ];

    private $website_items = [
        'pricing' => 'pricing',
        'howwework' => 'how we work',
        'faq' => 'faq',
        'blog' => 'blog',
        'contact' => 'contact',
        'login' => 'login',
        'register' => 'register',
        'dashboard' => 'dashboard',
        'setting' => 'setting',
        'settings' => 'settings',
        'order' => 'order',
        'orders' => 'orders',
        'invoices' => 'invoices',
        'invoice' => 'invoice',
        'balance' => 'balance',
        'logout' => 'logout',
        'transport' => 'transport',
        'subtitle2' => 'Global turkey logistics and transportation',
        'subtitle1' => 'services via sea, land and air.',
        'shipping' => 'shipping',
        'fee' => 'fee',
        'calculator' => 'calculator',
    ];
}
